# AUTOMATICALLY GENERATED by clan
{ ... }: {
  imports =
    let
      relPaths = builtins.fromJSON (builtins.readFile ./imports.json);
      paths = map (path: ./. + path) relPaths;
    in
    paths;
}
