{
  imports = [
    ../../modules/disko.nix
    ../../modules/shared.nix
    # enables GNOME desktop (optional)
    ../../modules/gnome.nix
  ];
  # Put your username here for login
  users.users.user.name = "<your-username>";

  # Set this for clan commands use ssh i.e. `clan machines update`
  # If you change the hostname, you need to update this line to root@<new-hostname>
  # This only works however if you have avahi running on your admin machine else use IP
  clan.core.networking.targetHost = "root@<IP>";

  # You can get your disk id by running the following command on the installer:
  # Replace <IP> with the IP of the installer printed on the screen or by running the `ip addr` command.
  # ssh root@<IP> lsblk --output NAME,ID-LINK,FSTYPE,SIZE,MOUNTPOINT
  disko.devices.disk.main.device = "/dev/disk/by-id/__CHANGE_ME__";

  # IMPORTANT! Add your SSH key here
  # e.g. > cat ~/.ssh/id_ed25519.pub
  users.users.root.openssh.authorizedKeys.keys = [
    ''
      __YOUR_SSH_KEY__
    ''
  ];
  /*
    After jon is deployed, uncomment the following line
    This will allow sara to share the VPN overlay network with jon
    The networkId is generated by the first deployment of jon
  */
  # clan.core.networking.zerotier.networkId = builtins.readFile ../../vars/per-machine/jon/zerotier/zerotier-network-id/value;
}
