name: checks
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: nix
    steps:
      - uses: actions/checkout@v3
      - run: nix run --refresh github:Mic92/nix-fast-build -- --no-nom --eval-workers 20
  test-links:
    runs-on: nix
    steps:
      - uses: actions/checkout@v3
      - run: nix run --refresh --inputs-from .# nixpkgs#lychee .
  test-impure:
    runs-on: nix
    steps:
      - uses: actions/checkout@v3
      - run: nix run .#impure-checks
