name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-docs:
    runs-on: nix
    steps:
      - uses: actions/checkout@v4
      - run: nix run .#deploy-docs
    env:
      SSH_HOMEPAGE_KEY: ${{ secrets.SSH_HOMEPAGE_KEY }}
