// There is an existing pagefind plugin for vite:
// https://github.com/Hugos68/vite-plugin-pagefind
//
// It's not used becuase:
// 1. It manually run the package manager's build command. This mean it needs to
//    detech which package manager is actually used, where it could have simply
//    run the pagefind's node API at vite build time and asks the user to run
//    the build command in the dev command.
// 2. It expects the build command to specify the output directory and then the
//    corresponding option passes to the vite plugin must match that value. This
//    means there are two sources of truth.
// 3. It can't do multiple plugin instances to index different folders

import type { PagefindServiceConfig } from "pagefind";
import type { PluginOption, UserConfig } from "vite";
import * as pagefind from "pagefind";
import pathutil from "node:path";
import pkg from "./package.json" with { type: "json" };
import { rm } from "node:fs/promises";

export interface PagefindIndexOptions {
  basePath?: string;
  baseUrl?: string;
  excerptLength?: number;
  indexWeight?: number;
  mergeFilter?: Record<string, unknown>;
  highlightParam?: string;
  language?: string;
  primary?: boolean;
  ranking?: PagefindRankingWeights;
}

export interface PagefindRankingWeights {
  termSimilarity?: number;
  pageLength?: number;
  termSaturation?: number;
  termFrequency?: number;
}

export interface PagefindSearchOptions {
  preload?: boolean;
  verbose?: boolean;
  filters?: Record<string, unknown>;
  sort?: Record<string, unknown>;
}

export type PagefindFilterCounts = Record<string, Record<string, number>>;

export interface PagefindSearchResults {
  results: PagefindSearchResult[];
  unfilteredResultCount: number;
  filters: PagefindFilterCounts;
  totalFilters: PagefindFilterCounts;
  timings: {
    preload: number;
    search: number;
    total: number;
  };
}

export interface PagefindSearchResult {
  id: string;
  score: number;
  words: number[];
  data: () => Promise<PagefindSearchFragment>;
}

export interface PagefindSearchFragment {
  url: string;
  raw_url?: string;
  content: string;
  raw_content?: string;
  excerpt: string;
  sub_results: PagefindSubResult[];
  word_count: number;
  locations: number[];
  weighted_locations: PagefindWordLocation[];
  filters: Record<string, string[]>;
  meta: Record<string, string>;
  anchors: PagefindSearchAnchor[];
}

export interface PagefindSubResult {
  title: string;
  url: string;
  locations: number[];
  weighted_locations: PagefindWordLocation[];
  excerpt: string;
  anchor?: PagefindSearchAnchor;
}

export interface PagefindWordLocation {
  weight: number;
  balanced_score: number;
  location: number;
}

export interface PagefindSearchAnchor {
  element: string;
  id: string;
  text?: string;
  location: number;
}

export interface Pagefind {
  debouncedSearch: (
    query: string,
    options?: PagefindSearchOptions,
    duration?: number,
  ) => Promise<PagefindSearchResults | null>;
  destroy: () => Promise<void>;
  filters: () => Promise<PagefindFilterCounts>;
  init: () => Promise<void>;
  mergeIndex: (
    indexPath: string,
    options?: Record<string, unknown>,
  ) => Promise<void>;
  options: (options: PagefindIndexOptions) => Promise<void>;
  preload: (term: string, options?: PagefindIndexOptions) => Promise<void>;
  search: (
    term: string,
    options?: PagefindSearchOptions,
  ) => Promise<PagefindSearchResults>;
}
export interface VitePluginPagefindOptions {
  readonly pluginInstance?: string;
  readonly siteDir?: string;
  readonly staticDir?: string;
  readonly assetsDir?: string;
  readonly bundleDir?: string;
  readonly base?: string;
  readonly pagefindOptions?: PagefindServiceConfig & {
    readonly glob?: string;
  };
}
// This plugin is used to run pagefind on files generated by SvelteKit. It must
// happen after SvelteKit has written the bundle to fs, which happened in the
// closeBundle hook:
// https://github.com/sveltejs/kit/blob/5239d988d5d7cae913d16bf2c876be591a1dccb4/packages/kit/src/exports/vite/index.js#L1385
export default function vitePluginPagefind({
  pluginInstance,
  siteDir = "build",
  staticDir = "static",
  assetsDir = "",
  bundleDir = "pagefind",
  base = "/",
  pagefindOptions,
}: VitePluginPagefindOptions): PluginOption {
  let root: string;
  let mode: string;
  let ssr: string | boolean;
  return {
    name: `${pkg.name}${pluginInstance ? `-${pluginInstance}` : ""}`,
    apply: "build",
    config(_config, { mode: m }): Omit<UserConfig, "plugins"> {
      mode = m;
      return {
        assetsInclude: ["**/pagefind.js", "**/pagefind-highlight.js"],
        build: {
          rollupOptions: {
            external: [
              `${base}${bundleDir}/pagefind.js`,
              `${base}${bundleDir}/pagefind-highlight.js`,
            ],
          },
        },
      };
    },
    async configResolved(config): Promise<void> {
      ({ root } = config);
      ({ ssr } = config.build);
      // Remove the results from the previous build
      await rm(pathutil.resolve(root, staticDir, bundleDir), {
        recursive: true,
        force: true,
      });
    },
    closeBundle: {
      sequential: true,
      async handler(): Promise<void> {
        if (ssr === false || ssr === "") {
          return;
        }
        const { glob, ...pfOpts } = pagefindOptions ?? {};

        // Create a Pagefind search index to work with
        const { index, errors } = await pagefind.createIndex(pfOpts);
        if (!index) {
          throw new Error(
            `Failed to create pagefind index:\n${errors.join("\n")}`,
          );
        }

        await index.addDirectory({
          path: pathutil.resolve(root, siteDir),
          ...(glob ? { glob } : {}),
        });
        await index.writeFiles({
          outputPath:
            mode === "development"
              ? pathutil.resolve(root, staticDir, bundleDir)
              : pathutil.resolve(root, assetsDir, bundleDir),
        });
      },
    },
  };
}
