{
  self,
  options,
  ...
}:
{
  imports = [
    ./distributed-service/flake-module.nix
  ];
  perSystem =
    {
      pkgs,
      lib,
      self',
      ...
    }:
    {
      devShells.inventory-schema = pkgs.mkShell {
        name = "clan-inventory-schema";
        inputsFrom = [
          self'.devShells.default
        ];
      };

      legacyPackages.jsonschema = (
        import ./clan-types {
          flakeOptions = options;
          inherit
            pkgs
            self
            lib
            self'
            ;
        }
      );

      packages.clan-types =
        pkgs.runCommand "clan-types"
          {
            nativeBuildInputs = [
              pkgs.jq
              self'.packages.datamodel-code-generator
            ];
          }
          ''
            mkdir -p $out

            jq . \
              ${builtins.toFile "typing.json" (builtins.toJSON self'.legacyPackages.jsonschema)} \
              >$out/typing.json

            header=$(cat <<'EOF'
            # DO NOT EDIT THIS FILE MANUALLY. IT IS GENERATED.
            # This file was generated by running `pkgs/clan-cli/clan_lib/nix_models/update.sh`
            #
            # fmt: off
            EOF
            )
            datamodel-codegen \
              --input $out/typing.json \
              --input-file-type jsonschema \
              --output-model-type typing.TypedDict \
              --target-python-version 3.13 \
              --skip-root-model \
              --use-union-operator \
              --use-title-as-name \
              --use-standard-collections \
              --use-field-description \
              --use-schema-description \
              --use-double-quotes \
              --use-frozen-field \
              --custom-file-header "$header" \
              --disable-future-imports \
              --output $out/typing.py
          '';

      legacyPackages.clan-service-module-interface =
        (pkgs.nixosOptionsDoc {
          options =
            (self.clanLib.evalService {
              modules = [
                { _docs_rendering = true; }
                {
                  options."#specialArgs" = lib.mkOption {
                    description = ''
                      Adidtional arguments passed to the module. Often referred to as `specialArgs`.

                      ```nix
                      {
                        # root directory of the clan
                        directory,
                        # clanLib - The clan library functions
                        clanLib,
                        # exports from all services
                        exports,
                        ...
                      }:
                      {
                        _class = "clan.service";
                        manifest.name = "example-service";

                        # ... elided
                      }
                      ```
                    '';
                  };
                }
              ];
              prefix = [ ];
            }).options;
          warningsAreErrors = true;
          transformOptions = self.clanLib.docs.stripStorePathsFromDeclarations;
        }).optionsJSON;
    };
}
