/* eslint-disable unicorn/no-null */
import type { Config } from "stylelint";
import { fileURLToPath } from "node:url";

export default {
  extends: ["stylelint-config-standard"],
  plugins: [
    "stylelint-use-logical",
    "stylelint-use-nesting",
    "stylelint-value-no-unknown-custom-properties",
    "stylelint-media-use-custom-media",
    "stylelint-order",
  ],
  rules: {
    "color-no-invalid-hex": true,
    "color-named": [
      "never",
      {
        ignoreProperties: ["black", "white"],
      },
    ],
    "declaration-no-important": true,
    // This rule doesn't work well for nested rules
    "no-descending-specificity": null,
    "csstools/use-logical": true,
    "csstools/use-nesting": true,
    "order/order": ["custom-properties", "rules", "at-rules"],
    // Adapted from
    // https://github.com/hudochenkov/stylelint-config-hudochenkov/blob/master/order.js
    "order/properties-order": [
      [
        "all",
        "content",
        "position",
        "inset",
        "inset-inline",
        "inset-inline-start",
        "inset-inline-end",
        "inset-block",
        "inset-block-start",
        "inset-block-end",
        "z-index",
        "display",
        "vertical-align",
        "flex",
        "flex-grow",
        "flex-shrink",
        "flex-basis",
        "flex-direction",
        "flex-flow",
        "flex-wrap",
        "grid",
        "grid-area",
        "grid-template",
        "grid-template-areas",
        "grid-template-rows",
        "grid-template-columns",
        "grid-row",
        "grid-row-start",
        "grid-row-end",
        "grid-column",
        "grid-column-start",
        "grid-column-end",
        "grid-auto-rows",
        "grid-auto-columns",
        "grid-auto-flow",
        "grid-gap",
        "grid-row-gap",
        "grid-column-gap",
        "gap",
        "row-gap",
        "column-gap",
        "place-content",
        "align-content",
        "justify-content",
        "place-items",
        "align-items",
        "justify-items",
        "place-self",
        "align-self",
        "justify-self",
        "order",
        "float",
        "clear",
        "object-fit",
        "object-position",
        "overflow",
        "overflow-x",
        "overflow-y",
        "overflow-scrolling",
        "clip",

        //
        "box-sizing",
        "inline-size",
        "min-inline-size",
        "max-inline-size",
        "block-size",
        "min-block-size",
        "max-block-size",
        "aspect-ratio",
        "margin",
        "margin-inline",
        "margin-inline-start",
        "margin-inline-end",
        "margin-block",
        "margin-block-start",
        "margin-block-end",
        "padding",
        "padding-inline",
        "padding-inline-start",
        "padding-inline-end",
        "padding-block",
        "padding-block-start",
        "padding-block-end",

        "color",
        "background",
        "background-color",
        "background-image",
        "background-attachment",
        "background-position",
        "background-position-x",
        "background-position-y",
        "background-clip",
        "background-origin",
        "background-size",
        "background-repeat",

        "border",
        "border-spacing",
        "border-collapse",
        "border-width",
        "border-style",
        "border-color",
        "border-inline-start",
        "border-inline-start-width",
        "border-inline-start-style",
        "border-inline-start-color",
        "border-inline-end",
        "border-inline-end-width",
        "border-inline-end-style",
        "border-inline-end-color",
        "border-block-start",
        "border-block-start-width",
        "border-block-start-style",
        "border-block-start-color",
        "border-block-end",
        "border-block-end-width",
        "border-block-end-style",
        "border-block-end-color",
        "border-radius",
        "border-start-start-radius",
        "border-start-end-radius",
        "border-end-start-radius",
        "border-end-end-radius",
        "border-image",
        "border-image-source",
        "border-image-slice",
        "border-image-width",
        "border-image-outset",
        "border-image-repeat",
        "box-decoration-break",
        "box-shadow",
        "outline",
        "outline-width",
        "outline-style",
        "outline-color",
        "outline-offset",
        "table-layout",
        "caption-side",
        "empty-cells",
        "list-style",
        "list-style-position",
        "list-style-type",
        "list-style-image",

        //
        "font",
        "font-weight",
        "font-style",
        "font-variant",
        "font-size-adjust",
        "font-stretch",
        "font-size",
        "font-family",
        "src",
        "line-height",
        "letter-spacing",
        "quotes",
        "counter-increment",
        "counter-reset",
        "-ms-writing-mode",
        "text-align",
        "text-align-last",
        "text-decoration",
        "text-emphasis",
        "text-emphasis-position",
        "text-emphasis-style",
        "text-emphasis-color",
        "text-indent",
        "text-justify",
        "text-outline",
        "text-transform",
        "text-wrap",
        "text-overflow",
        "text-overflow-ellipsis",
        "text-overflow-mode",
        "text-shadow",
        "white-space",
        "word-spacing",
        "word-wrap",
        "word-break",
        "overflow-wrap",
        "tab-size",
        "hyphens",
        "interpolation-mode",

        //
        "opacity",
        "visibility",
        "filter",
        "resize",
        "cursor",
        "pointer-events",
        "user-select",

        //
        "unicode-bidi",
        "direction",
        "columns",
        "column-span",
        "column-width",
        "column-count",
        "column-fill",
        "column-rule",
        "column-rule-width",
        "column-rule-style",
        "column-rule-color",
        "break-before",
        "break-inside",
        "break-after",
        "page-break-before",
        "page-break-inside",
        "page-break-after",
        "orphans",
        "widows",
        "zoom",
        "max-zoom",
        "min-zoom",
        "user-zoom",
        "orientation",
        "fill",
        "stroke",

        //
        "transition",
        "transition-delay",
        "transition-timing-function",
        "transition-duration",
        "transition-property",
        "transform",
        "transform-origin",
        "animation",
        "animation-name",
        "animation-duration",
        "animation-play-state",
        "animation-timing-function",
        "animation-delay",
        "animation-iteration-count",
        "animation-direction",
        "animation-fill-mode",
      ],
      {
        unspecified: "bottom",
      },
    ],
  },
} satisfies Config;

export function base({
  customProperties = [],
  customMedia = [],
}: {
  customProperties?: URL[] | URL;
  customMedia?: URL[] | URL;
} = {}): NonNullable<Config["rules"]> {
  return {
    "csstools/value-no-unknown-custom-properties": [
      true,
      {
        importFrom: (Array.isArray(customProperties)
          ? customProperties
          : [customProperties]
        ).map((url) => fileURLToPath(url)),
      },
    ],
    "csstools/media-use-custom-media": [
      "known",
      {
        importFrom: (Array.isArray(customMedia)
          ? customMedia
          : [customMedia]
        ).map((url) => fileURLToPath(url)),
      },
    ],
  };
}
