import type { PluginOption } from "vite";
import { opendir, readFile, writeFile } from "node:fs/promises";
import pathutl from "node:path";
import pkg from "./package.json" with { type: "json" };

export interface Replacement {
  from: string | RegExp;
  to: string;
}

// This plugin is mainly used to replace strings for files generated by
// SvelteKit. The replacement must happen after SvelteKit has written the bundle
// to fs, which happened in the closeBundle hook:
// https://github.com/sveltejs/kit/blob/5239d988d5d7cae913d16bf2c876be591a1dccb4/packages/kit/src/exports/vite/index.js#L1385
export default function vitePluginReplace({
  dir,
  test,
  replacements,
}: {
  dir: string;
  test: RegExp;
  replacements: Replacement[];
}): PluginOption {
  let root: string;
  let ssr: string | boolean;
  return {
    name: pkg.name,
    apply: "build",
    configResolved(config): void {
      ({ root } = config);
      ({ ssr } = config.build);
    },
    closeBundle: {
      sequential: true,
      async handler(): Promise<void> {
        if (ssr === false || ssr === "") {
          return;
        }
        for await (const dirent of await opendir(pathutl.resolve(root, dir), {
          recursive: true,
        })) {
          const path = pathutl.join(dirent.parentPath, dirent.name);
          if (!test.test(path)) {
            continue;
          }
          let content = await readFile(path, "utf8");
          let replaced = false;
          for (const replacement of replacements) {
            const newContent = content.replaceAll(
              replacement.from,
              replacement.to,
            );
            if (newContent === content) {
              continue;
            }
            replaced = true;
            content = newContent;
          }
          if (replaced) {
            await writeFile(path, content);
          }
        }
      },
    },
  };
}
