{
 "title": "Infrastructure Health",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "${hostname}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$hostname\"} / node_memory_MemTotal_bytes{instance=\"$hostname\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$hostname\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=\"$hostname\", mountpoint=\"/\"} * 100 / node_filesystem_size_bytes{instance=\"$hostname\", mountpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=\"$hostname\", mountpoint=\"/nix\"} * 100 / node_filesystem_size_bytes{instance=\"$hostname\", mountpoint=\"/nix\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (rate({instance=\"$hostname\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Service Health",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "nixos_systemd_unit_state{instance=\"$hostname\"} == 1",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=\"$hostname\", mountpoint=\"/boot\"} * 100 / node_filesystem_size_bytes{instance=\"$hostname\", mountpoint=\"/boot\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}