import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

// const fontPath = ;
const roboto = localFont({
  src: [
    {
      path: "../fonts/truetype/Roboto-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    // {
    //   path: "./Roboto-Italic.woff2",
    //   weight: "400",
    //   style: "italic",
    // },
    // {
    //   path: "./Roboto-Bold.woff2",
    //   weight: "700",
    //   style: "normal",
    // },
    // {
    //   path: "./Roboto-BoldItalic.woff2",
    //   weight: "700",
    //   style: "italic",
    // },
  ],
});

// const inter =
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
